dataset:
  name: "EuroSAT"

  paths:
    train: "data/raw/train"
    validation: "data/raw/val"
    test: "data/raw/test"

  image:
    size: 224
    channels: 3

  classes:
    - AnnualCrop
    - Forest
    - HerbaceousVegetation
    - Highway
    - Industrial
    - Pasture
    - PermanentCrop
    - Residential
    - River
    - SeaLake

  preprocessing:
    normalize: true
    augmentation: true

  dataloader:
    batch_size: 32
    num_workers: 4
    shuffle: true